---
- name: Install OpenSSH client
  apt: name=openssh-client state=present

- name: Install OpenSSH server
  apt: name=openssh-server state=present

- name: Push OpenSSH daemon configuration file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config

- name: Create OpenSSH systemd unit file directory
  file: path=/etc/systemd/system/sshd.socket.d state=directory

- name: Push OpenSSH socket unit file
  template: src=sshd-socket-override.conf.j2 dest=/etc/systemd/system/sshd.socket.d/override.conf
  notify:
    - restart sshd

- name: Enable and start OpenSSH
  service: name=ssh enabled=yes state=started
  when: ssh.enable_sshd is defined and ssh.enable_sshd == True

- name: Disable and stop OpenSSH
  service: name=sshd.service enabled=no state=stopped
  when: ssh.enable_sshd is defined and ssh.enable_sshd == False

- name: Install sshfs
  apt: name=sshfs state=present

- name: Install autossh
  apt: name=autossh state=present

- name: Copy fuse configuration file
  copy: src=fuse.conf dest=/etc/fuse.conf

- name: Install keychain
  apt: name=keychain state=present

- name: Make directory for user SSH key
  file: path=/home/{{ user.name }}/.ssh state=directory owner={{ user.name }} group={{ user.group }}

- name: Install Mosh
  apt: name=mosh state=present
