---
- name: create fonts directory
  file:
    path: "/usr/share/fonts/truetype/jetbrains"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: font exists
  shell: "ls /usr/share/fonts/truetype/jetbrains/JetBrainsMono*"
  register: font_exists
  ignore_errors: yes

- name: download font
  when: font_exists is failed
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip
    dest: "/usr/share/fonts/truetype/jetbrains"
    remote_src: yes
